import Container from '@/components/layouts/Container';
import Footer from '@/components/layouts/Footer';
import Header from '@/components/layouts/Header';
import { Poppins } from 'next/font/google';
import './globals.css';

import localFont from 'next/font/local';

const poppins = Poppins({
  weight: ['100', '200', '400', '500', '600', '800'],
});

export const banglaCustomFont = localFont({
  src: './../fonts/mayaboti-normal.ttf',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${poppins.className} grid grid-rows-[auto_1fr_auto] min-h-dvh`}>
        <Header />
        <main className='min-w-0'>
          <Container className='h-full'>{children}</Container>
        </main>
        <Footer />
      </body>
    </html>
  );
}
